### ISSUE TITLE
Peer review: Onderzoeksvraag 👥

### ISSUE THREAD

**Issue by Jelmerovereem** [deannabosschert/functional-programming#10]
# ⚙️ Onderzoeksvraag
### Begrijp je de onderzoeksvraag die in de Readme staat?   
_Zeker! Duidelijk geformuleerd.👍_

### Welke (sub)vragen roept deze onderzoeksvraag bij je op?

- _Zijn er bepaalde plekken/parkeer plaatsen waar het heel druk is geworden door het coronavirus? (bijv. bij supermarkten omdat mensen als een gek gingen hamsteren)🅿️_

- _Zijn er parkeerplekken die nu belemmerd worden omdat er een coronateststraat op staat?⛔_

- _Hoeveel effort doen parkeerbeheerders om ervoor te zorgen dat bepaalde maatregelen worden nageleefd?😰_

### Welke data zou ik nog meer zou kunnen gebruiken bij deze vraag?
_[RIVM covid-19 dataset](https://data.rivm.nl/covid-19/)_
_[Bronnen voor datasets over covid-19](https://www.databronnencovid19.nl/)_

**Geen data, maar misschien wel handige bronnen**
[https://www.verkeersnet.nl/parkeren/35060/extra-coronaregels-leiden-niet-tot-minder-parkeertransacties/](https://www.verkeersnet.nl/parkeren/35060/extra-coronaregels-leiden-niet-tot-minder-parkeertransacties/)
[https://www.verkeersnet.nl/parkeren/35241/parkeren-in-coronatijd-zo-regel-je-het-goed-als-beheerder/](https://www.verkeersnet.nl/parkeren/35241/parkeren-in-coronatijd-zo-regel-je-het-goed-als-beheerder/)

![we've got issues](https://media.giphy.com/media/4Mni3cxTuKHDi/giphy.gif)
![solution](https://media.giphy.com/media/3o7TKD78kaHoXDOPOo/giphy.gif)

**Comment by Jelmerovereem** [comment]
Als je nog vragen hebt over de feedback; feel free to comment! 💬

**Comment by chelseadoeleman** [comment]
Ik sluit mij aan bij de feedback van Jelmer! 😊 Super interessante onderzoeksvraag!

**Comment by deannabosschert** [comment]
Oeps, wel gelezen en gereageerd in de standup maar nog niet hieronder; thanks voor je uitgebreide feedback!
Superhandige deelvragen ook, ik heb ze meegenomen in m'n concept!
