### ISSUE TITLE
Peer review: Onderzoeksvraag 👥

### ISSUE THREAD

**Issue by ZekkieB** [deannabosschert/functional-programming#9]
# ⚙️ Onderzoeksvraag
### Begrijp je de onderzoeksvraag die in de Readme staat?   
Ja!

### Welke (sub)vragen roept deze onderzoeksvraag bij je op?

Hoe ver liggen de corona teststraten van elkaar af.

Wat is de gemiddelde capaciteit van een teststraat.

Van hoelaat tot hoelaat is een teststraat open.

### Welke data zou ik nog meer zou kunnen gebruiken bij deze vraag?

[Geolocatie parkeer gebieden](https://opendata.rdw.nl/Parkeren/Open-Data-Parkeren-GEOMETRIE-GEBIED/nsk3-v9n7)

![we've got issues](https://media.giphy.com/media/4Mni3cxTuKHDi/giphy.gif)

**Comment by deannabosschert** [comment]
Ik wacht nog even tot ik weet of er überhaupt een dataset met de locaties van de coronateststraten beschikbaar is, anders kan ik de vragen die daarmee te maken hebben misschien beter laten vallen

Verder heb ik je dataset-suggestie toegevoegd!
